### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by benjchristensen** [google/safevarargs#2]
I have been messing around with this but not been able to make it work. Considering this project looks like an experiment that never went anywhere, does this actually work? 

If it does work can you please provide an example of how to compile with Java 7 (or 8) to Java 6 (major version 50) using this?

The source code is all Java 6 compliant except for the use of `@SafeVararg`, which is what I assume this project is for.

**Comment by cgruber** [comment]
Yeah - in the end we simply turned off unsafe varargs warnings entirely so this wasn't really needed.  

That said, You would NOT compile with java 7 or 8, you would compile with Java 6 includign this in your compile-time classpath, but then omit the jar in your runtime classpath.  But I cannot truly tell you that it works, because we abandoned the effort.

**Comment by benjchristensen** [comment]
Good to know, thanks for the insight, and information on how to use it.
